name: Deploy Market Analysis API

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test imports and basic functionality
      run: |
        python -c "
        # Test that all imports work
        from app.config import settings
        from app.models import SectorAnalysisResponse, HealthCheck
        from app.rate_limiter import limiter
        from app.auth import cleanup_expired_sessions
        from app.data_collector import DataCollector
        from app.ai_analyzer import AIAnalyzer
        print('✅ All imports successful!')
        
        # Test FastAPI app creation
        from fastapi import FastAPI
        from app.main import app
        print('✅ FastAPI app created successfully!')
        "
    
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t market-analysis-api .
    
    - name: Test Docker container
      run: |
        # Run container in background
        docker run -d -p 8000:8000 --name test-container \
          -e GEMINI_API_KEY=test-key \
          market-analysis-api
        
        # Wait for container to start
        sleep 10
        
        # Test health endpoint
        curl -f http://localhost:8000/health || exit 1
        
        # Stop container
        docker stop test-container
        docker rm test-container
    
    - name: Deploy notification
      run: |
        echo "🎉 Build successful! Ready for deployment."
        echo "Container image: market-analysis-api"
